version: '3'

services:
  covid-daily-cases:
    entrypoint: /bin/sh './entrypoint-prod.sh'
    container_name: covid_daily_cases
    build: .
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - .:/app/
